export const AVATAR_EMOJIS = [
  "🧑",
  "👩",
  "🧑‍🦱",
  "👱‍♀️",
  "🧑‍🦰",
  "👨",
  "👩‍🦱",
  "🧔",
  "👧",
  "🤓",
  "💪",
  "🏃",
  "🏊",
  "⚽",
  "🏀",
];

// Узбекистан - Viloyatlar (Области)
export const VILOYATLAR = [
  "Qoraqalpogʻiston",
  "Xorazm viloyati",
  "Navoiy viloyati",
  "Buxoro viloyati",
  "Samarqand viloyati",
  "Qashqadaryo viloyati",
  "Surxondaryo viloyati",
  "Jizzax viloyati",
  "Sirdaryo viloyati",
  "Toshkent viloyati",
  "Namangan viloyati",
  "Fargʻona viloyati",
  "Andijon viloyati",
  "Toshkent shahri",
];

// Иерархия: Viloyat -> Tumanlar/Shaharlar
export const VILOYATLAR_VA_TUMANLAR: Record<string, string[]> = {
  "Qoraqalpogʻiston": [
    "Amudaryo",
    "Beruniy",
    "Chimboy",
    "Ellikqalʼa",
    "Kegeyli",
    "Moʻynoq",
    "Nukus",
    "Qanlikoʻl",
    "Qoʻngʻirot",
    "Qoraoʻzak",
    "Shumanay",
    "Taxtakoʻpir",
    "Toʻrtkoʻl",
    "Xoʻjayli",
    "Taxiatosh",
    "Boʻzatov",
    // Shaharlar
    "Nukus (shahar)",
    "Beruniy (shahar)",
    "Toʻrtkoʻl (shahar)",
    "Taxiatosh (shahar)",
    "Qoʻngʻirot (shahar)",
    "Mangʻit (shahar)",
  ],
  "Xorazm viloyati": [
    "Bogʻot",
    "Gurlan",
    "Xonqa",
    "Hazorasp",
    "Xiva",
    "Qoʻshkoʻpir",
    "Shovot",
    "Urganch",
    "Yangiariq",
    "Yangibozor",
    "Tuproqqalʼa",
    // Shaharlar
    "Urganch (shahar)",
    "Xiva (shahar)",
    "Pitnak (shahar)",
    "Gurlan (shahar)",
    "Hazorasp (shahar)",
  ],
  "Navoiy viloyati": [
    "Konimex",
    "Karmana",
    "Qiziltepa",
    "Xatirchi",
    "Navbahor",
    "Nurota",
    "Tomdi",
    "Uchquduq",
    // Shaharlar
    "Navoiy (shahar)",
    "Zarafshon (shahar)",
    "Uchquduq (shahar)",
    "Nurota (shahar)",
  ],
  "Buxoro viloyati": [
    "Olot",
    "Buxoro",
    "Gʻijduvon",
    "Jondor",
    "Kogon",
    "Qorakoʻl",
    "Qorovulbozor",
    "Peshku",
    "Romitan",
    "Shofirkon",
    "Vobkent",
    // Shaharlar
    "Buxoro (shahar)",
    "Kogon (shahar)",
    "Gʻijduvon (shahar)",
    "Romitan (shahar)",
    "Qorakoʻl (shahar)",
  ],
  "Samarqand viloyati": [
    "Bulungʻur",
    "Ishtixon",
    "Jomboy",
    "Kattaqoʻrgʻon",
    "Qoʻshrabot",
    "Narpay",
    "Nurobod",
    "Oqdaryo",
    "Paxtachi",
    "Payariq",
    "Pastdargʻom",
    "Samarqand",
    "Toyloq",
    "Urgut",
    // Shaharlar
    "Samarqand (shahar)",
    "Kattaqoʻrgʻon (shahar)",
    "Urgut (shahar)",
    "Bulungʻur (shahar)",
    "Ishtixon (shahar)",
  ],
  "Qashqadaryo viloyati": [
    "Chiroqchi",
    "Dehqonobod",
    "Gʻuzor",
    "Qamashi",
    "Qarshi",
    "Koson",
    "Kasbi",
    "Kitob",
    "Mirishkor",
    "Muborak",
    "Nishon",
    "Shahrisabz",
    "Yakkabogʻ",
    "Koʻkdala",
    // Shaharlar
    "Qarshi (shahar)",
    "Shahrisabz (shahar)",
    "Kitob (shahar)",
    "Koson (shahar)",
    "Muborak (shahar)",
  ],
  "Surxondaryo viloyati": [
    "Angor",
    "Boysun",
    "Denov",
    "Jarqoʻrgʻon",
    "Qiziriq",
    "Qumqoʻrgʻon",
    "Muzrabot",
    "Oltinsoy",
    "Sariosiyo",
    "Sherobod",
    "Shoʻrchi",
    "Termiz",
    "Uzun",
    "Bandixon",
    // Shaharlar
    "Termiz (shahar)",
    "Denov (shahar)",
    "Sherobod (shahar)",
    "Boysun (shahar)",
  ],
  "Jizzax viloyati": [
    "Arnasoy",
    "Baxmal",
    "Doʻstlik",
    "Forish",
    "Gʻallaorol",
    "Sharof Rashidov",
    "Mirzachoʻl",
    "Paxtakor",
    "Yangiobod",
    "Zomin",
    "Zafarobod",
    "Zarbdor",
    // Shaharlar
    "Jizzax (shahar)",
    "Gʻallaorol (shahar)",
    "Paxtakor (shahar)",
    "Doʻstlik (shahar)",
  ],
  "Sirdaryo viloyati": [
    "Oqoltin",
    "Boyovut",
    "Guliston",
    "Xovos",
    "Mirzaobod",
    "Sayxunobod",
    "Sardoba",
    "Sirdaryo",
    // Shaharlar
    "Guliston (shahar)",
    "Yangiyer (shahar)",
    "Shirin (shahar)",
    "Sirdaryo (shahar)",
  ],
  "Toshkent viloyati": [
    "Bekobod",
    "Boʻstonliq",
    "Boʻka",
    "Chinoz",
    "Qibray",
    "Ohangaron",
    "Oqqoʻrgʻon",
    "Parkent",
    "Piskent",
    "Quyi Chirchiq",
    "Oʻrta Chirchiq",
    "Yangiyoʻl",
    "Yuqori Chirchiq",
    "Zangiota",
    // Shaharlar
    "Nurafshon (shahar)",
    "Angren (shahar)",
    "Bekobod (shahar)",
    "Chirchiq (shahar)",
    "Olmaliq (shahar)",
    "Ohangaron (shahar)",
    "Yangiyoʻl (shahar)",
  ],
  "Namangan viloyati": [
    "Chortoq",
    "Chust",
    "Kosonsoy",
    "Mingbuloq",
    "Namangan",
    "Norin",
    "Pop",
    "Toʻraqoʻrgʻon",
    "Uchqoʻrgʻon",
    "Uychi",
    "Yangiqoʻrgʻon",
    // Shaharlar
    "Namangan (shahar)",
    "Chust (shahar)",
    "Kosonsoy (shahar)",
    "Pop (shahar)",
    "Uchqoʻrgʻon (shahar)",
  ],
  "Fargʻona viloyati": [
    "Oltiariq",
    "Bagʻdod",
    "Beshariq",
    "Buvayda",
    "Dangʻara",
    "Fargʻona",
    "Furqat",
    "Qoʻshtepa",
    "Quva",
    "Rishton",
    "Soʻx",
    "Toshloq",
    "Uchkoʻprik",
    "Oʻzbekiston",
    "Yozyovon",
    // Shaharlar
    "Fargʻona (shahar)",
    "Qoʻqon (shahar)",
    "Margʻilon (shahar)",
    "Quva (shahar)",
    "Rishton (shahar)",
  ],
  "Andijon viloyati": [
    "Andijon",
    "Asaka",
    "Baliqchi",
    "Boʻston",
    "Buloqboshi",
    "Izboskan",
    "Jalaquduq",
    "Xoʻjaobod",
    "Qoʻrgʻontepa",
    "Marhamat",
    "Oltinkoʻl",
    "Paxtaobod",
    "Shahrixon",
    "Ulugʻnor",
    // Shaharlar
    "Andijon (shahar)",
    "Asaka (shahar)",
    "Shahrixon (shahar)",
    "Xonobod (shahar)",
  ],
  "Toshkent shahri": [
    "Bektemir",
    "Chilonzor",
    "Yashnobod",
    "Mirobod",
    "Mirzo Ulugʻbek",
    "Sergeli",
    "Shayxontohur",
    "Olmazor",
    "Uchtepa",
    "Yakkasaroy",
    "Yunusobod",
    "Yangihayot",
  ],
};

// Для обратной совместимости (будет использоваться как Viloyatlar)
export const Viloyatlar = VILOYATLAR;

// Все Tumanlar (районы) - для обратной совместимости
export const TUMANLAR = Object.values(VILOYATLAR_VA_TUMANLAR).flat();
