import { sportTurlari } from "./sports-data";
import type {
  Klub,
  Musobaqa,
  SportJoy,
  Sportchi,
  Yangilik,
  Yutuq,
} from "./types";

export { sportTurlari };

export const sportJoylari: SportJoy[] = [
  {
    id: 1,
    nomi: "Farg'ona Davlat Universiteti Stadioni",
    manzil: "Farg'ona shahri, Mustaqillik ko'chasi 19",
    kenglik: 40.3839,
    uzunlik: 71.7873,
    tuman: "Farg'ona",
    sport_turlari: ["Futbol", "Yugurish"],
    telefon: "+998 73 244 0101",
    ish_vaqti: "06:00 - 22:00",
    reyting: 4.5,
  },
  {
    id: 2,
    nomi: "Sport Majmuasi 'Yoshlik'",
    manzil: "Farg'ona shahri, Al-Farg'oniy ko'chasi 5",
    kenglik: 40.3801,
    uzunlik: 71.791,
    tuman: "Farg'ona",
    sport_turlari: ["Basketbol", "Voleybol", "Tennis"],
    telefon: "+998 73 245 5555",
    ish_vaqti: "07:00 - 21:00",
    reyting: 4.8,
  },
  {
    id: 3,
    nomi: "Suzish Havzasi 'Delfin'",
    manzil: "Marg'ilon shahri, Buyuk Ipak Yo'li ko'chasi 12",
    kenglik: 40.4684,
    uzunlik: 71.7247,
    tuman: "Marg'ilon",
    sport_turlari: ["Suzish"],
    telefon: "+998 73 253 1234",
    ish_vaqti: "08:00 - 20:00",
    reyting: 4.2,
  },
  {
    id: 4,
    nomi: "Boks Maktabi",
    manzil: "Farg'ona shahri, Navoiy ko'chasi 45",
    kenglik: 40.3756,
    uzunlik: 71.7823,
    tuman: "Farg'ona",
    sport_turlari: ["Boks", "Karate"],
    telefon: "+998 73 246 7890",
    ish_vaqti: "09:00 - 19:00",
    reyting: 4.6,
  },
  {
    id: 5,
    nomi: "Tennis Klubi 'Ace'",
    manzil: "Quva tumani, Markaziy ko'cha 8",
    kenglik: 40.5236,
    uzunlik: 72.0712,
    tuman: "Quva",
    sport_turlari: ["Tennis", "Badminton"],
    telefon: "+998 73 354 4321",
    ish_vaqti: "07:00 - 20:00",
    reyting: 4.3,
  },
];

export const musobaqalar: Musobaqa[] = [
  {
    id: 1,
    nomi: "Universitet Futbol Kubogi 2026",
    kategoriya: "Futbol",
    sana: "2026-03-15",
    joy: "Farg'ona Davlat Universiteti Stadioni",
    ishtirokchilar_soni: 24,
    maksimal_ishtirokchilar: 32,
    holat: "kelgusi",
    rasm_emoji: "⚽",
    tavsif:
      "Farg'ona viloyati universitetlari o'rtasidagi an'anaviy futbol musobaqasi",
    mukofotlar:
      "1-o'rin: 5,000,000 so'm\n2-o'rin: 3,000,000 so'm\n3-o'rin: 1,500,000 so'm",
  },
  {
    id: 2,
    nomi: "Basketbol Chempionati",
    kategoriya: "Basketbol",
    sana: "2026-02-20",
    joy: "Sport Majmuasi 'Yoshlik'",
    ishtirokchilar_soni: 16,
    maksimal_ishtirokchilar: 16,
    holat: "faol",
    rasm_emoji: "🏀",
    tavsif: "Talabalar o'rtasidagi basketbol chempionati",
    mukofotlar: "1-o'rin: 3,000,000 so'm\n2-o'rin: 2,000,000 so'm",
  },
  {
    id: 3,
    nomi: "Voleybol Turniri",
    kategoriya: "Voleybol",
    sana: "2026-01-10",
    joy: "Sport Majmuasi 'Yoshlik'",
    ishtirokchilar_soni: 12,
    maksimal_ishtirokchilar: 12,
    holat: "yakunlangan",
    rasm_emoji: "🏐",
    tavsif: "Qishki voleybol turniri",
    mukofotlar: "G'olib jamoaga sovg'alar",
  },
  {
    id: 4,
    nomi: "Shaxmat Olimpiadasi",
    kategoriya: "Shaxmat",
    sana: "2026-04-05",
    joy: "FarDU Kutubxonasi",
    ishtirokchilar_soni: 8,
    maksimal_ishtirokchilar: 64,
    holat: "kelgusi",
    rasm_emoji: "♟️",
    tavsif: "Intellektual sport musobaqasi",
  },
  {
    id: 5,
    nomi: "Yugurish Marafoni",
    kategoriya: "Yugurish",
    sana: "2026-05-01",
    joy: "Farg'ona shahri markazi",
    ishtirokchilar_soni: 150,
    maksimal_ishtirokchilar: 500,
    holat: "kelgusi",
    rasm_emoji: "🏃",
    tavsif: "5 km va 10 km masofalar",
  },
];

export const sportchilar: Sportchi[] = [
  {
    id: 1,
    ism: "Islomov Sardor",
    sport: "Futbol",
    fakultet: "Axborot texnologiyalari",
    guruh: "AT-21",
    daraja: "Professional",
    medallar: 12,
    yulduzlar: 5,
    avatar_emoji: "🧑‍🦱",
    telefon: "+998 90 123 4567",
    tug_yil: 2003,
    bio: "Jamoaning eng yaxshi hujumchisi",
    klub: "FarDU Futbol Klubi",
    klub_id: 1,
  },
  {
    id: 2,
    ism: "Karimova Dilnoza",
    sport: "Basketbol",
    fakultet: "Iqtisodiyot",
    guruh: "IQ-22",
    daraja: "Professional",
    medallar: 8,
    yulduzlar: 4,
    avatar_emoji: "👩",
    telefon: "+998 91 234 5678",
    tug_yil: 2004,
    bio: "Ayollar jamoasining lideri",
    klub: "Basketbol Klubi",
    klub_id: 2,
  },
  {
    id: 3,
    ism: "Rahimov Aziz",
    sport: "Voleybol",
    fakultet: "Fizika-matematika",
    guruh: "FM-20",
    daraja: "Havaskor",
    medallar: 5,
    yulduzlar: 3,
    avatar_emoji: "🧑",
    tug_yil: 2002,
    bio: "Voleybol jamoasi a'zosi",
  },
  {
    id: 4,
    ism: "Toshmatov Bobur",
    sport: "Boks",
    fakultet: "Jismoniy tarbiya",
    guruh: "JT-23",
    daraja: "Professional",
    medallar: 15,
    yulduzlar: 5,
    avatar_emoji: "💪",
    telefon: "+998 93 345 6789",
    tug_yil: 2001,
    bio: "Viloyat chempioni",
    klub: "Boks Klubi",
    klub_id: 3,
  },
  {
    id: 5,
    ism: "Sobirova Malika",
    sport: "Tennis",
    fakultet: "Xorijiy tillar",
    guruh: "XT-21",
    daraja: "Havaskor",
    medallar: 3,
    yulduzlar: 3,
    avatar_emoji: "👧",
    tug_yil: 2003,
    bio: "Tennis bo'yicha iqtidorli sportchi",
  },
  {
    id: 6,
    ism: "Qodirov Jahongir",
    sport: "Shaxmat",
    fakultet: "Matematika",
    guruh: "M-22",
    daraja: "Professional",
    medallar: 20,
    yulduzlar: 5,
    avatar_emoji: "🤓",
    telefon: "+998 94 456 7890",
    tug_yil: 2002,
    bio: "Respublika shaxmat chempioni",
  },
  {
    id: 7,
    ism: "Abdullayev Sherzod",
    sport: "Futbol",
    fakultet: "Axborot texnologiyalari",
    guruh: "AT-22",
    daraja: "Havaskor",
    medallar: 4,
    yulduzlar: 3,
    avatar_emoji: "🧑‍🦰",
    tug_yil: 2004,
    klub: "FarDU Futbol Klubi",
    klub_id: 1,
  },
  {
    id: 8,
    ism: "Ergasheva Nodira",
    sport: "Suzish",
    fakultet: "Biologiya",
    guruh: "B-21",
    daraja: "Professional",
    medallar: 10,
    yulduzlar: 4,
    avatar_emoji: "👱‍♀️",
    telefon: "+998 95 567 8901",
    tug_yil: 2003,
    bio: "Suzish bo'yicha viloyat rekordchisi",
  },
];

export const klublar: Klub[] = [
  {
    id: 1,
    nomi: "FarDU Futbol Klubi",
    tavsif: "Farg'ona Davlat Universiteti rasmiy futbol klubi",
    sport_turi: "Futbol",
    rasm_emoji: "⚽",
    azolar_soni: 25,
    lider: {
      id: 1,
      ism: "Islomov Sardor",
      sport: "Futbol",
      medallar: 12,
      yulduzlar: 5,
    },
  },
  {
    id: 2,
    nomi: "Basketbol Klubi",
    tavsif: "Talabalar basketbol jamoasi",
    sport_turi: "Basketbol",
    rasm_emoji: "🏀",
    azolar_soni: 18,
    lider: {
      id: 2,
      ism: "Karimova Dilnoza",
      sport: "Basketbol",
      medallar: 8,
      yulduzlar: 4,
    },
  },
  {
    id: 3,
    nomi: "Boks Klubi",
    tavsif: "Professional bokschilar uchun klub",
    sport_turi: "Boks",
    rasm_emoji: "🥊",
    azolar_soni: 15,
    lider: {
      id: 4,
      ism: "Toshmatov Bobur",
      sport: "Boks",
      medallar: 15,
      yulduzlar: 5,
    },
  },
  {
    id: 4,
    nomi: "Shaxmat Klubi",
    tavsif: "Aqliy sport ixlosmandlari uchun",
    sport_turi: "Shaxmat",
    rasm_emoji: "♟️",
    azolar_soni: 30,
  },
  {
    id: 5,
    nomi: "Voleybol Klubi",
    tavsif: "Erkaklar va ayollar voleybol jamoalari",
    sport_turi: "Voleybol",
    rasm_emoji: "🏐",
    azolar_soni: 20,
  },
];

export const yutuqlar: Yutuq[] = [
  {
    id: 1,
    nomi: "Viloyat chempioni",
    sportchi: { id: 1, ism: "Islomov Sardor" },
    musobaqa: "Farg'ona viloyat futbol chempionati",
    medal_turi: "oltin",
    medal_soni: 1,
    sana: "2025-12-15",
    rasm_emoji: "🥇",
  },
  {
    id: 2,
    nomi: "2-o'rin",
    sportchi: { id: 2, ism: "Karimova Dilnoza" },
    musobaqa: "Respublika basketbol kubogi",
    medal_turi: "kumush",
    medal_soni: 1,
    sana: "2025-11-20",
    rasm_emoji: "🥈",
  },
  {
    id: 3,
    nomi: "Viloyat chempioni",
    sportchi: { id: 4, ism: "Toshmatov Bobur" },
    musobaqa: "Boks bo'yicha viloyat chempionati",
    medal_turi: "oltin",
    medal_soni: 1,
    sana: "2025-10-10",
    rasm_emoji: "🥇",
  },
  {
    id: 4,
    nomi: "Respublika chempioni",
    sportchi: { id: 6, ism: "Qodirov Jahongir" },
    musobaqa: "O'zbekiston shaxmat chempionati",
    medal_turi: "oltin",
    medal_soni: 1,
    sana: "2025-09-05",
    rasm_emoji: "🥇",
  },
  {
    id: 5,
    nomi: "3-o'rin",
    sportchi: { id: 8, ism: "Ergasheva Nodira" },
    musobaqa: "Suzish bo'yicha respublika musobaqasi",
    medal_turi: "bronza",
    medal_soni: 1,
    sana: "2025-08-25",
    rasm_emoji: "🥉",
  },
];

export const yangiliklar: Yangilik[] = [
  {
    id: 1,
    sarlavha: "Futbol jamoasi viloyat chempionatida g'olib bo'ldi!",
    mazmun:
      "FarDU futbol jamoasi qattiq kurashlar davomida viloyat chempionatida birinchi o'rinni egalladi. Jamoa kapitani Islomov Sardor eng yaxshi futbolchi deb topildi. Musobaqa davomida jamoamiz 8 ta o'yin o'tkazib, barchasida g'alaba qozondi.",
    kategoriya: "Futbol",
    rasm_emoji: "⚽",
    sana: "2025-12-16",
    layklar: 45,
    izohlar_soni: 12,
  },
  {
    id: 2,
    sarlavha: "Yangi sport majmuasi qurilmoqda",
    mazmun:
      "Universitet hududida zamonaviy sport majmuasi qurilishi boshlandi. Majmua 2026-yil oxirigacha foydalanishga topshirilishi rejalashtirilgan. U yerda suzish havzasi, basketbol va voleybol maydonchalari bo'ladi.",
    kategoriya: "Umumiy",
    rasm_emoji: "🏗️",
    sana: "2025-12-10",
    layklar: 32,
    izohlar_soni: 8,
  },
  {
    id: 3,
    sarlavha: "Shaxmat bo'yicha trening boshlanmoqda",
    mazmun:
      "Yangi o'quv yili boshlanishi munosabati bilan shaxmat bo'yicha bepul treninglar e'lon qilinadi. Barcha darajadagi talabalar qatnashishi mumkin. Treninglar har hafta seshanba va payshanba kunlari o'tkaziladi.",
    kategoriya: "Shaxmat",
    rasm_emoji: "♟️",
    sana: "2025-12-05",
    layklar: 28,
    izohlar_soni: 5,
  },
  {
    id: 4,
    sarlavha: "Basketbol jamoasi yangi mavsumga tayyor",
    mazmun:
      "Universitetimiz basketbol jamoasi yangi mavsumga tayyorgarlik ko'rmoqda. Jamoaga yangi o'yinchilar qabul qilindi va intensiv mashg'ulotlar boshlandi.",
    kategoriya: "Basketbol",
    rasm_emoji: "🏀",
    sana: "2025-12-01",
    layklar: 19,
    izohlar_soni: 3,
  },
];

export const fakultetlar = [
  "Mexanika-mashinasozlik fakulteti",
  "Energetika muhandisligi fakulteti",
  "Kimyo texnologiya fakulteti",
  "Arxitektura va qurilish fakulteti",
  "Ishlab chiqarishda boshqaruv fakulteti",
  "Yengil sanoat va to'qimachilik fakulteti",
  "Axborot texnologiyalari va telekommunikatsiya fakulteti",
];
export const guruhlar = [
  "AT-21",
  "AT-22",
  "IQ-22",
  "FM-20",
  "JT-23",
  "XT-21",
  "M-22",
  "B-21",
];
